Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,9 +18,9 @@ jobs:
     steps:
       - uses: actions/checkout@master
       - name: Update Build Tools
-      - run: git submodule foreach git pull origin master
+        run: git submodule foreach git pull origin master
       - name: Setup PHP
-      - uses: nanasess/setup-php@master
+        uses: nanasess/setup-php@master
         with:
           php-version: ${{ matrix.php }}
           run: find . -name "*.php" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
@@ -31,14 +31,14 @@ jobs:
     steps:
       - uses: actions/checkout@master
       - name: Update Build Tools
-      - run: git submodule foreach git pull origin master
+        run: git submodule foreach git pull origin master
       - name: Checking Sign off
-      - run: if php other/buildTools/check-signed-off.php github | grep "Error:"; then php buildTools/check-signed-off.php github; exit 1; fi
+        run: if php other/buildTools/check-signed-off.php github | grep "Error:"; then php buildTools/check-signed-off.php github; exit 1; fi
       - name: Checking Licensing
-      - run: find . -name "*.php" -exec php buildTools/check-license.php {} 2>&1 \; | grep "Error:"; if find . -name "*.php" -exec php buildTools/check-license.php {} 2>&1 \; | grep "Error:"; then exit 1; fi
+        run: find . -name "*.php" -exec php buildTools/check-license.php {} 2>&1 \; | grep "Error:"; if find . -name "*.php" -exec php buildTools/check-license.php {} 2>&1 \; | grep "Error:"; then exit 1; fi
       - name: Checking End of File
-      - run: find . -name "*.php" -exec php buildTools/check-eof.php {} 2>&1 \; | grep "Error:"; if find . -name "*.php" -exec php buildTools/check-eof.php {} 2>&1 \; | grep "Error:"; then exit 1; fi
+        run: find . -name "*.php" -exec php buildTools/check-eof.php {} 2>&1 \; | grep "Error:"; if find . -name "*.php" -exec php buildTools/check-eof.php {} 2>&1 \; | grep "Error:"; then exit 1; fi
       - name: Javascript LINT
-      - uses: tj-actions/eslint-changed-files@v4
-      - with:
-        config-path: buildTools/eslintrc
+        uses: tj-actions/eslint-changed-files@v4
+        with:
+          config-path: buildTools/eslintrc
